Ecommerce1/Ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('cart/',include('cart.urls')),
    path('search/',include('search.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Ecommerce1/cart/urls.py
from django.contrib import admin
from django.urls import path
from cart import views
app_name='cart'
urlpatterns = [
    path('addtocart/<int:i>',views.addtocart,name="addtocart"),
    path('cart',views.cart_view,name='cart'),
    path('remove/<int:i>',views.cart_remove,name="remove"),
    path('delete/<int:i>',views.cart_delete,name="delete"),
    path("orderform",views.order_form,name="orderform"),
    path('status/<u>',views.payment_status,name="status"),
    path('orderview',views.order_view,name="orderview"),
]

Ecommerce1/search/urls.py
from django.contrib import admin
from django.urls import path
from search import views
app_name="search"
urlpatterns = [

    path('', views.search_products, name="search"),
]

Ecommerce1/shop/urls.py
from django.contrib import admin
from django.urls import path
from shop import views
app_name="shop"
urlpatterns = [

    path('', views.categories, name="categories"),
    path('products/<int:p>',views.products,name="products"),
    path('details_products/<int:p>',views.details_products,name="details_products"),
    path('register/',views.register, name="register"),
    path('login/',views.user_login,name="login"),
    path('logout/',views.user_logout,name="logout"),
    path('addcat',views.add_categories,name="addcat"),
    path('addpro',views.add_products,name="addpro"),
    path('addstock/<int:p>',views.addstock,name="addstock"),
]

Ecommerce1/cart/models.py
from django.db import models
from shop.models import Products
from django.contrib.auth.models import User
class Cart(models.Model):
      product=models.ForeignKey(Products,on_delete=models.CASCADE)
      user=models.ForeignKey(User,on_delete=models.CASCADE)
      quantity=models.IntegerField(default=1)
      date_added=models.DateTimeField(auto_now_add=True)

def subtotal(self):
  return self.quantity*self.product.price

class Payment(models.Model):
      name=models.CharField(max_length=30)
      amount=models.IntegerField()
      order_id=models.CharField(max_length=30,blank=True)
      razorpay_payment_id=models.CharField(max_length=30,blank=True)
      paid=models.BooleanField(default=False)
class Order_details(models.Model):
      product=models.ForeignKey(Products,on_delete=models.CASCADE)
      user=models.ForeignKey(User,on_delete=models.CASCADE)
      no_of_items=models.IntegerField()
      address=models.CharField(max_length=30)
      phone_no=models.BigIntegerField()
      pin=models.IntegerField()
      order_id=models.CharField(max_length=30,blank=True)
      ordered_date=models.DateTimeField(auto_now_add=True)

      payment_status=models.CharField( max_length=20,default="pending")
      delivery_status=models.CharField(max_length=20,default="pending")

Ecommerce1/search/models.py
from django.db import models

# Create your models here.

Ecommerce1/cart/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from cart.models import Cart,Payment,Order_details
from django.contrib.auth import login
from shop.models import Products
from django.contrib.auth.models import User
import razorpay


@login_required
def addtocart(request,i):
    p=Products.objects.get(id=i)
    u=request.user
    try:
        c=Cart.objects.get(product=p,user=u)
        if(p.stock>0):
          c.quantity+=1
          c.save()
          p.stock-=1
          p.save()
    except:
        if(p.stock>0):
           c=Cart.objects.create(product=p,user=u,quantity=1)
           c.save()
           p.stock-=1
           p.save()
    return redirect('cart:cart')
@login_required
def cart_view(request):
    u=request.user

    c=Cart.objects.filter(user=u)
    total=0
    for i in c:
        total+=i.quantity*i.product.price
    context={'cart':c,'total':total}
    return render(request,'cart.html',context)
@login_required
def cart_remove(request,i):
    p=Products.objects.get(id=i)
    u=request.user
    try:
        c = Cart.objects.get(product=p, user=u)
        if (c.quantity>1):
            c.quantity-= 1
            c.save()
            p.stock+= 1
            p.save()
        else:
          c.delete()
          p.stock+=1
          p.save()

    except:
        pass
    return redirect('cart:cart')
@login_required
def cart_delete(request,i):
    p = Products.objects.get(id=i)
    u = request.user
    c = Cart.objects.get(product=p,user=u)
    c.delete()
    p.stock+=c.quantity
    p.save()
    return redirect('cart:cart')
@login_required
def order_form(request):
    if(request.method=="POST"):
         address=request.POST['a']
         phone=request.POST['p']
         pin=request.POST['pi']
         u=request.user
         c=Cart.objects.filter(user=u)
         total=0
         for i in c:
           total+=i.quantity*i.product.price
         total1=int(total*100)

         client=razorpay.Client(auth=('rzp_test_5jhhCdnuLFQ9Ct','ceulEBU7BajFMWSlYU0S8LEm'))
         response_payment=client.order.create(dict(amount=total1,currency="INR"))
         print(response_payment)
         order_id=response_payment['id']#retrive the order_id from response
         status=response_payment['status']#retrive the status from response
         if(status == "created"): #if status is created then storeorder_id in payment and order_details
            p=Payment.objects.create(name=u.username,amount=total,order_id=order_id)
            p.save
            for i in c:#for each item cretaesa record inside order_details table
               o=Order_details.objects.create(product=i.product,user=u,no_of_items=i.quantity,address=address,phone_no=phone,pin=pin,order_id=order_id)
               o.save()
         response_payment['name']=u.username
         context={'payment':response_payment}
         return render(request,'payment.html',context)




    return render(request,'orderform.html')

from django.views.decorators.csrf import csrf_exempt
@csrf_exempt
def payment_status(request,u):
    usr = User.objects.get(username=u)
    if not request.user.is_authenticated:
     login(request,usr)
    if(request.method=="POST"):
        response=request.POST
        print(response)
        param_dict={
                   'razorpay_order_id':response['razorpay_order_id'],
                   'razorpay_payment_id': response['razorpay_payment_id'],
                   'razorpay_signature': response['razorpay_signature']
                }
        client=razorpay.Client(auth=('rzp_test_5jhhCdnuLFQ9Ct','ceulEBU7BajFMWSlYU0S8LEm'))
        print(client)
        try:
                 status=client.utility.verify_payment_signature(param_dict)#to check theauthentication of the razorpay signature
                 print(status)
                 p=Payment.objects.get(order_id=response['razorpay_order_id'])
                 p.razorpay_payment_id=response['razorpay_payment_id']
                 p.paid=True
                 p.save()
                 o=Order_details.objects.filter(order_id=response['razorpay_order_id'])
                 for i in o:
                     i.payment_status="completed"
                     i.save()

                 c=Cart.objects.filter(user=usr)# filter all records matching withparticular user
                 c.delete()
        except:
               pass
    return render(request,'payment_status.html',{'status':status})
@login_required
def order_view(request):
    u=request.user
    o=Order_details.objects.filter(user=u)
    print(o)
    context={'orders':o}
    return render(request,'order_view.html',context)

Ecommerce1/search/views.py
from django.shortcuts import render
from shop.models import Products

from django.db.models import Q
def search_products(request):
     if(request.method=="POST"):
          query=request.POST['q']
          if query:
             p=Products.objects.filter(Q(name__icontains=query) | Q(desc__icontains=query))
             context={'pro':p,'query':query}#filter the records matching with query
     return render(request,'search.html',context)

Ecommerce1/templates/add_categories.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container px-2 bg-secondary">
<h2 class="text-center mt-3">Add Category Details </h2>
<form method="POST" enctype="multipart/form-data">
{% csrf_token %}
    <div class="mb-3">
  <label class="form-label">Name</label>
<input type="text" class="form-control" name="n" placeholder="Enter Category Name">
</div>
<div class="mb-3">
<label class="form-label">image</label>
  <input type="file" class="form-control" name="i" >
</div>
<div class="mb-3">
<label class="form-label">Description</label>
  <input type="text" class="form-control" name="d" placeholder="Write Category Description">
</div>
<div class="mb-3">
    <input type="submit" class="form-control" >
</div>
</form>
</div>
{% endblock %}

Ecommerce1/templates/add_products.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container px-2 bg-secondary">
<h2 class="text-center mt-3">Add Product Details </h2>
<form method="POST"  enctype="multipart/form-data">
{% csrf_token %}
    <div class="mb-3">
  <label class="form-label">Name</label>
<input type="text" class="form-control" name="n" placeholder="Enter Product Name">
</div>
<div class="mb-3">
<label class="form-label">image</label>
  <input type="file" class="form-control" name="i" >
</div>
<div class="mb-3">
<label class="form-label">Description</label>
  <input type="text" class="form-control" name="d" placeholder="Write Category Description">
</div>
     <div class="mb-3">
  <label class="form-label">Stock</label>
<input type="text" class="form-control" name="s" placeholder="Enter Stock">
</div>
     <div class="mb-3">
  <label class="form-label">Price</label>
<input type="text" class="form-control" name="p" placeholder="Enter Price">

</div>
      <div class="mb-3">
  <label class="form-label">Category:</label>
<select name="c" id="">
    {% for i in links %}
    <option value="{{i.name}}">{{i.name}}</option>
    {% endfor %}

</select>
</div>

<div class="mb-3">
    <input type="submit" class="form-control" >
</div>
</form>
</div>
{% endblock %}

Ecommerce1/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
   <head>
      <!-- Basic -->
      <meta charset="utf-8" />
      <meta http-equiv="X-UA-Compatible" content="IE=edge" />
      <!-- Mobile Metas -->
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
      <!-- Site Metas -->
      <meta name="keywords" content="" />
      <meta name="description" content="" />
      <meta name="author" content="" />
      <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" type="">
      <title>myshop</title>
      <!-- bootstrap core css -->
      <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />
      <!-- font awesome style -->
      <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" />
      <!-- Custom styles for this template -->
      <link href="{% static 'css/style.css' %}" rel="stylesheet" />
      <!-- responsive style -->
      <link href="{% static 'css/responsive.css' %}" rel="stylesheet" />
   </head>
   <body>
      <div class="hero_area">
         <!-- header section strats -->
         <header class="header_section">

            <div class="container-fluid">
               <nav class="navbar navbar-expand-lg custom_nav-container ">
                  <a class="navbar-brand fs-3 fw-bold"> <h2>MYSHOP</h2></a>
                  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar_toggler-icon"></span>
                  </button>
                  <div class="collapse navbar-collapse" id="navbarSupportedContent">
                     <ul class="navbar-nav mx-auto mb-2 mb-lg-0 fs-5 fw-bold">
                        <li class="nav-item">
                           <a class="nav-link" aria-current="page" href="{% url 'shop:categories' %}">Home</a>
                        </li>


                       <li class="nav-item dropdown">

                           <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true"> <span class="nav-label">Allcategories <span class="caret"></span></a>
                           <ul class="dropdown-menu">
                               {% for i in links %}
                               <li><a href="{% url 'shop:products' i.id %} ">{{i.name}}</a></li>
                               {% endfor %}
                           </ul>
                          </li>

                            {% if user.is_authenticated %}

                            {% if user.is_superuser == False %}<!--normal user -->
                         <li class="nav-item">
                           <a class="nav-link" href="{% url 'cart:cart' %}"><i class="fa fa-shopping-cart fs-2" aria-hidden="true"></i><sup class="mx-2 fs-5">{{c}}</sup></a>
                        </li>
                         <li class="nav-item">
                              <a class="nav-link" aria-current="page" href="{% url 'cart:orderview' %}">your orders</a>
                          </li>
                           {% else %}

                         <li class="nav-item">
                          <a class="nav-link" aria-current="page" href="{% url 'shop:addcat' %}">AddCategories</a>


                        </li>
                        <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'shop:addpro' %}">AddProducts</a>
                       </li>
                       {% endif %}
                       <li class="nav-item">
                           <a class="nav-link" href="{% url 'shop:logout' %}">logout</a>
                        </li>
                          {% else %}

                        <li class="nav-item">
                           <a class="nav-link"  aria-current="page" href="{% url 'shop:register' %}">Register</a>
                        </li>
                        <li class="nav-item">
                           <a class="nav-link" aria-current="page" href="{% url 'shop:login' %}">Login</a>
                        </li>
                          {% endif %}
                        <form class="d-flex justify content-between" method="POST" action="{% url 'search:search' %}">

                          {% csrf_token %}
                          <input class="border border-dark  w-50" type="search" name="q"  placeholder="search" aria-label="search">


                        </form>

                   </ul>
                  </div>
               </nav>
            </div>
         </header>
         <!-- end header section -->
         <!-- slider section -->
          <div class="container-fluid">
{% block content %}
{% endblock %}
       </div>



   <!--footer-->
    <footer>
         <div class="container">
            <div class="row">
               <div class="col-md-4">
                   <div class="full">
                      <div class="logo_footer">
                        <p><strong><h2>MYSHOP</h2></strong>
                      </div>
                      <div class="information_f">
                        <p><strong>ADDRESS:</strong> Plankal thadathi(h) pathanamthitta p.o</p>
                        <p><strong>TELEPHONE:</strong> +91 987 654 3210</p>
                        <p><strong>EMAIL:</strong> myshop@gmail.com</p>
                      </div>
                   </div>
               </div>
               <div class="col-md-8">
                  <div class="row">
                  <div class="col-md-7">
                     <div class="row">
                        <div class="col-md-6">
                     <div class="widget_menu">
                        <h3>Menu</h3>
                        <ul>
                           <li><a href="#">Home</a></li>
                           <li><a href="#">About</a></li>
                           <li><a href="#">Services</a></li>
                           <li><a href="#">Testimonial</a></li>
                           <li><a href="#">your orders</a></li>
                           <li><a href="#">search</a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6">
                     <div class="widget_menu">
                        <h3>Account</h3>
                        <ul>
                           <li><a href="#">Account</a></li>
                           <li><a href="#">Checkout</a></li>
                           <li><a href="#">Login</a></li>
                           <li><a href="#">Register</a></li>
                           <li><a href="#">Shopping</a></li>
                           <li><a href="#">Widget</a></li>
                        </ul>
                     </div>
                  </div>
                     </div>
                  </div>
                  <div class="col-md-5">
                     <div class="widget_menu">
                        <h3>Newsletter</h3>
                        <div class="information_f">
                          <p>Subscribe by our newsletter and get update protidin.</p>
                        </div>
                        <div class="form_sub">
                           <form>
                              <fieldset>
                                 <div class="field">
                                    <input type="email" placeholder="Enter Your Mail" name="email" />
                                    <input type="submit" value="Subscribe" />
                                 </div>
                              </fieldset>
                           </form>
                        </div>
                     </div>
                  </div>
                  </div>
               </div>
            </div>
         </div>
      </footer>
      <!-- footer end -->
      <div class="cpy_">
         <p class="mx-auto">© 2024 ALL Rights <a href="https://html.design/"></a><br>

            Distributed By <a href="https://themewagon.com/" target="_blank"> dhanya manoj</a>

         </p>
      </div>
      <!-- jQery -->
      <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
      <!-- popper js -->
      <script src="{% static 'js/popper.min.js' %}"></script>
      <!-- bootstrap js -->
      <script src="{% static 'js/bootstrap.js' %}"></script>
      <!-- custom js -->
      <script src="{% static 'js/custom.js' %}"></script>
   </body>
</html>

Ecommerce1/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div  class="container bg-secondary">
<h3 class="text-center text-dark ">Shopping cart</h3>
 <div class="container mt-5 px-3 " style="margin-bottom:100px">
     <div class="row ">

         <div class="col-8">
           <table class="table table-bordered text-center">

          <tr><th colspan="8">Cart items</th></tr>
           {% for i in cart %}
         <tr>
            <td class="p-3"><img src="{{i.product.image.url}}" height="100px" width="100%"></td>
            <td class="p-3">product:{{i.product.name}}</td>
            <td class="p-3">Quantity:{{i.quantity}}<br>
             unit price:{{i.product.price}}</td>
            <td class="p-3">subtotal:{{i.subtotal}}</td>
            <td>
                {% if i.product.stock > 0 %}
                <a href="{% url 'cart:addtocart' i.product.id %}"><i class="fa fa-plus-circle text-light fs-5" aria-hidden="true"></i></a>
                <a href="{% url 'cart:remove' i.product.id %}"><i class="fa fa-minus-circle text-light fs-5" aria-hidden="true"></i></a>
                <a href="{% url 'cart:delete' i.product.id %}"><i class="fa fa-trash text-light fs-4 " aria-hidden="true"></i></a>
                {% else %}
                <a href="{% url 'cart:remove' i.product.id %}"><i class="fa fa-minus-circle text-light fs-5" aria-hidden="true"></i></a>
                <a href="{% url 'cart:delete' i.product.id %}"><i class="fa fa-trash text-light fs-5 " aria-hidden="true"></i></a>
                {% endif %}
            </td>

         </tr>
         {% endfor %}
         </table>
   </div>




<div class="cols-6">
         <table class="table table-bordered p-3">
             <tr><th colspan="5">Check out</th></tr>
             <tr><td>Total:{{total}}</td></tr>
         </table>
        <div class="d-flex justify-between">
           <a href="{% url 'cart:orderform' %}" class="btn btn-light p-1 mt-2">PlaceOrder</a>

         <a href="" class="btn btn-light  p-1 mt-2">Continue shopping </a>
        </div>

       </div>
         </div>
 </div>
</div>
{% endblock %}

Ecommerce1/templates/categories.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="card text-black">
  <img src="{% static 'images/img11.jpg' %}"  height="600px" width="100%" class="card-img" alt="...">
  <div class="card-img-overlay">
    <h1 class="card-title mx-auto">ONLINE JEWELLERY</h1>
      <div class="detail-box ">
                                 <h1 >
                                    <span>
                                    Sale 25% Off
                                    </span>
                                    <br>
                                    On Everything
                                     <br>
                                    <button>ShopNow</button>
                                 </h1>


  </div>
</div>
<div class="container mt-4 p-3"  style="margin-bottom:100px;">
    <h2 class="text-center"><b>OUR COLLECTIONS</b></h2><br>
    <p style="text-align:justify;line-height:2;font-size:20px;">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.</p>
</div>
<div class="container mt- p-5 " style="margin-bottom:100px">
<div class="row">
{% for i in cat %}
<div class="col-sm-4">
<div class="card mx-auto border border-3 border-primary" style="width: 18rem;">
  <img src="{{i.image.url}}"  height="200px" width="100%">
  <div class="card-body">
    <center>
        <h1 class="card bg-light">{{i.name}}</h1>
    <h6 class="card-title">{{i.desc}}</h6>
       <a href="{% url 'shop:products' i.id %}" class="btn btn-primary">Product</a>
    </center>
  </div>
  </div>
  </div>
  {% endfor %}
</div>
</div>
</div>
{% endblock %}

Ecommerce1/templates/details.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
<div class="card mb-3 mt-7 mx-auto p-4" style="max-width: 640px;">
  <div class="row g-0">
    <div class="col-md-4 p-3">
      <img src="{{products.image.url}}" class="rounded-start" alt="..." height="300px" width="100%">
    </div>
    <div class="col-md-8 lh-lg ps-5">
      <div class="card-body mt-3">
        <h5 class="card-title">{{products.name}}</h5>
        <p class="card-title">{{products.desc}}</p>
        <p class="card-text">{{products.price}}</p>
        <p class="card-text">{{products.stock}}</p>
        <h4> product details</h4>
        <p class="cart-text" style="Line-height:2;text-align:justify">{{products.desc}}</p>
         {% if user.is_superuser == True %}
          {% if products.stock > 0 %}
        <h5>Product in stock</h5>
        <a href="{% url 'shop:addstock' products.id %}" class="btn btn-secondary fw-bold mt-3 mb-2 text-center"> ADD STOCK</a>
         {% else %}
        <h5>Product out of stock </h5>
        <a href="{% url 'shop:addstock' products.id %}" class="btn btn-secondary fw-bold mt-3 mb-2 text-center"> ADD STOCK</a>
        {% endif %}
        {% else %}
         {% if products.stock > 0 %}
        <a href="{% url 'cart:addtocart' products.id %}" class="btn btn-success">Add to cart</a>
        {% else %}
        <h5>Out of stock </h5>
        {% endif %}

        {% endif %}

      </div>
    </div>
  </div>
</div>
</div>
{% endblock %}

Ecommerce1/templates/login.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
 <div class="container px-2 bg-secondary">
<h2 class="text-center mt-3">login </h2>
<form method="POST" >
    {% csrf_token %}
    <div class="mb-3">
  <label class="form-label">username</label>
   <input type="text" class="form-control"  name="u" placeholder="username">
</div>
<div class="mb-3">
  <label  class="form-label">password</label>
  <input type="password" class="form-control" name="p"  placeholder="password">
</div>
<div class="mb-3">
    <input type="submit" value="submit" >
</div>
</form>
</div>

{% endblock %}

Ecommerce1/templates/new.html
<div class="container mt-5 " style="margin-bottom:100px">
<div class="row">
{% for i in cat %}
<div class="col-sm-4">
<div class="card mx-auto border border-3 border-light" style="width: 18rem;">
  <img src="{{i.image.url}}" class="card-img-top"  height="200px" width="100%">
  <div class="card-bod ">
    <center>
    <h5 class="card-title">{{i.name}}</h5>
       <p class="card-title">{{i.description}}</p>
       <a href="{%  url 'shop:products' i.id %}" class="btn btn-primary">Product</a>
    </center>
  </div>
  </div>
  </div>
  {% endfor %}
</div>
</div>
</div>

Ecommerce1/templates/order_view.html
<!DOCTYPE html>

{% extends 'base.html' %}
{% block content %}
<div class="container mt-5 p-3 mx auto" style="margin-bottom:100px;">
    <h2 class=" text-center mx-auto p-3 bg-primary">ORDER DETAILS</h2>
{% for i in orders %}
    <div class="card mb-3" style="max-width:540px;">

  <div class="row g-0">
    <div class="col-md-4">
      <img src="{{i.product.image.url}}" class="img-fluid rounded-start" alt="...">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <p class="card-title">Product Name:{{i.product.name}}</p>
        <p class="card-text">Order Total:{{i.product.price}}</p>
        <p class="card-text">Quantity:{{i.no_of_items}}</p>
        <p class="card-text">Ordered on:{{i.ordered_date}}</p>
          <p class="card-text">Ordered id:{{i.ordered_id}}</p>
         <p class="card-text">Delivery status:{{i.delivery_status}}</p>
      </div>
      </div>
    </div>
  </div>
      {% endfor %}
  </div>

{% endblock %}

Ecommerce1/templates/orderform.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container px-2 bg-secondary">
<h2 class="text-center mt-3">Billing page</h2>
<form method="POST">
{% csrf_token %}
    <div class="mb-3">
  <label class="form-label">Address</label>
<input type="text" class="form-control" name="a" placeholder="enter address">
</div>
<div class="mb-3">
<label class="form-label">Phone</label>
  <input type="number" class="form-control" name="p" placeholder="phone">
</div>
<div class="mb-3">
<label class="form-label">pin</label>
  <input type="password" class="form-control" name="pi" placeholder="pin number">
</div>
<div class="mb-3">
    <input type="submit" class="form-control" >
</div>
</form>
</div>
{% endblock %}

Ecommerce1/templates/payment.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container nt-5 p-5 bg-light w-50" style="margin-bottom:100px">

    <form action="{% url 'cart:status' payment.name %}" class="fs-4 text-center p-5" method="POST">
<script
   src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="rzp_test_5jhhCdnuLFQ9Ct"// Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="{{payment.amount}}" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-order_id="{{payment.id}}"// Replace with the order_id generated by you in the backend.
    data-buttontext="Pay with Razorpay"
    data-name="Myshop"
    data-description="shop smarter,shop here"
    data-image="https://example.com/your_logo.jpg"
    data-prefill.name="{{payment.name}}"
    data-prefill.email="myshop@gmail.com"
    data-theme.color="#F37254"
></script>
<input type="hidden" custom="Hidden Element" name="hidden"/>
</form>
</div>
{% endblock %}

Ecommerce1/templates/payment_status.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container mt-5 p-5 bg-light w-50" style="margin-bottom:100px;">
    {% if status == True %}
    <h2>payment successful</h2>
    (% else %}
     <h2>payment failed.try gain later</h2>
    {% endif %}
</div>
{% endblock %}

Ecommerce1/templates/search.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>Login</title>
{% endblock %}
{% block content %}
<center>
    <div class="container mt-5 p-3 style="...">
<h2>you have searched for {{query}}</h2>
<div class="row">
    {% for i in pro %}
<div class="col-sm-4 p-3">
<div class="card mx-auto border border-3 border-light" style="width:20rem;">
   <img src="{{i.image.url}}" height="200px" width="100%" class="card-img-top" alt="...">
      <div class="card-body text-center">
        <h5 class="card-title mb-3">{{i.name}}</h5>
        <h5 class="card-title mb-3">{{i.price}}</h5>
        <a href="{% url 'shop:details_products' i.id %}" class="btn btn-primary">DETAILS</a>

  </div>
  </div>
  </div>
    {% empty %}
    <h3 class="text-center">No result found</h3>

  {% endfor %}
</div>

</center>
{% endblock %}